# Site
name: "Republiqueta"
title: "Republiqueta"
description: "Impressões sobre o Brasil presentemente."
logo: 'assets/images/logo.png'
logo_yb: 'assets/images/logo_yb.png'
favicon: 'assets/images/favicon.png'
baseurl:
google_analytics: 'UA-175442418-1'
disqus: ''
mailchimp-list: 'https://gmail.us10.list-manage.com/subscribe/post?u=9384e21d0b0cc53d1c95e6322&amp;id=20e9b56205'
include: ["_pages"]
permalink: /:title/

future: false

# Authors
authors:
  igorL:
    name: Igor Lopes
    display_name: Igor Lopes
    avatar: 'assets/images/igorL.jpg'
    description: "Apaixonado por arte e cultura, geek e sempre pensando em algo."
  igorG:
    name: Igor Gonçalves
    display_name: Igor Gonçalves
    avatar: 'assets/images/igorG.jpg'
    description: "Jovem latino-americano, internacionalista e um entusiasta das causas entudantis."
  juan:
    name: Juan Comamala
    display_name: Juan Comamala
    avatar: 'assets/images/juan.jpg'
    description: "O conforto não me move, não me inspira, não me instiga. O desconforto me move. Esse, me possui e me evolui."
  lg:
    name: Luís Gustavo Pessoa Sales
    display_name: Luís Gustavo
    avatar: 'assets/images/lg.jpg'
    email: pessoasales@usp.br
    twitter: https://twitter.com/lgpsales
    description: "Cada vez menos interessado em definições e cada vez mais encantado com as relações."
  mari:
    name: Mariana Freire
    display_name: Mariana Freire
    avatar: 'assets/images/mari.jpg'
    description: "Jovem, curiosa, nerd e fascinada pelas coisas simples da vida."
  mends:
    name: Mends
    display_name: Mends
    avatar: 'assets/images/mends.jpg'
    description: "44 anos sendo uma errata ambulante. Não me siga, porque não faço a mínima ideia pra onde estou indo. Não sabia o que queria com 18, não é agora que vou saber."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, .jekyl-cache]
