# Site
name: "Republiqueta"
title: "Republiqueta"
description: "Impressões sobre o Brasil presentemente."
logo: 'assets/images/logo.png'
logo_yb: 'assets/images/logo_yb.png'
favicon: 'assets/images/favicon.png'
baseurl:
google_analytics: 'UA-175442418-1'
disqus: ''
mailchimp-list: 'https://gmail.us10.list-manage.com/subscribe/post?u=9384e21d0b0cc53d1c95e6322&amp;id=20e9b56205'
include: ["_pages"]
permalink: /:title/

future: false

# Authors
authors:
  ad+:
    name: Além do mais
    display_name: Além do mais
    avatar: 'assets/images/alem.png'
    description: "Neste podcast, Guilherme Cruz e Luís Gustavo buscam entender esta navelouca chamada Brasil através de uma leitura política e jurídica de seus principais acontecimentos."
  bruno:
    name: Bruno Henrique
    display_name: Bruno Henrique
    avatar: 'assets/images/bruno.jpg'
    description: "Professor de filosofia no expediente e leitor apaixonado de filosofia, literatura e psicanálise fora do expediente. E se escrevo é por mera ousadia."
  cafe:
    name: Papo no Café
    display_name: Papo no Café
    avatar: 'assets/images/cafe.jpg'
    description: "nesse podcast, misturamos café, política, análises e um bom papo entre amigos."
  gabi:
    name: Gabriela Morgado
    display_name: Gabriela Morgado
    avatar: 'assets/images/gabi.jpg'
    description: "Sou o que invento nas experiências do dia a dia."
  guilherme:
    name: Guilherme Cruz
    display_name: Guilherme Cruz
    avatar: 'assets/images/guilherme.jpg'
    description: "Me equilibrando entre olhar o passado e viver no presente."
  igorL:
    name: Igor Lopes
    display_name: Igor Lopes
    avatar: 'assets/images/igorL.jpg'
    description: "Apaixonado por arte e cultura, geek e sempre pensando em algo."
  igorG:
    name: Igor Gonçalves
    display_name: Igor Gonçalves
    avatar: 'assets/images/igorG.jpg'
    description: "Jovem latino-americano, internacionalista e um entusiasta das causas entudantis."
  juan:
    name: Juan Comamala
    display_name: Juan Comamala
    avatar: 'assets/images/juan.jpg'
    description: "O conforto não me move, não me inspira, não me instiga. O desconforto me move. Esse, me possui e me evolui."
  lais:
    name: Laís Marachini
    display_name: Laís Marachini
    avatar: 'assets/images/lais.jpg'
    description: "Reflexões de uma jovem cientista social com uma pitada de ironia para ficar mais leve."
  lg:
    name: Luís Gustavo Pessoa Sales
    display_name: Luís Gustavo
    avatar: 'assets/images/lg.jpg'
    email: pessoasales@usp.br
    twitter: https://twitter.com/lgpsales
    description: "Cada vez menos interessado em definições e cada vez mais encantado com as relações."
  manoL:
    name: Mano Lyee
    display_name: Mano Lyee
    avatar: 'assets/images/mano-lyee.jpg'
    description: "Acreditando que somente com cultura de roda de conversas e diálogos pode se levar mais conhecimento e informações através da arte, cultura poesia e cidadania -o presente é a arma do futuro, com a munição do passado."
  mari:
    name: Mariana Freire
    display_name: Mariana Freire
    avatar: 'assets/images/mari.jpg'
    description: "Jovem, curiosa, nerd e fascinada pelas coisas simples da vida."
  mends:
    name: Mends
    display_name: Mends
    avatar: 'assets/images/mends.jpg'
    description: "44 anos sendo uma errata ambulante. Não me siga, porque não faço a mínima ideia pra onde estou indo. Não sabia o que queria com 18, não é agora que vou saber."
  rafa:
    name: Rafaela Cáffaro
    display_name: Rafaela Cáffaro
    avatar: 'assets/images/rafa.jpg'
    description: "Gosta da leveza que não me tira do chão."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, .jekyl-cache]

collections:
  autores:
    output: true
